[package]
name = "micrograd-rs-digits"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
csv = "1.3"
flate2 = "1.0"
image = "0.25"
micrograd-rs = { git = "https://github.com/mickvangelderen/micrograd-rs.git" }
rand = "0.8"
ureq = "2.10"
