[package]
name = "micrograd-rs-digits"
version = "0.1.0"
edition = "2024"

[dependencies]
micrograd-rs = { git = "https://github.com/mickvangelderen/micrograd-rs.git", rev = "72cae0cb790dad51340e6a9e6cc1ec272c107813" }
ureq = "2.10"
anyhow = "1.0"
csv = "1.3"
flate2 = "1.0"
rand = "0.8"
image = "0.25"
